import express from "express";
import { buscarEmpresaPorID, buscarEmpresas, buscarFiliais, buscarFilialPorID, buscarPessoaPorID } from "../controladores/controlador.js";
const app = express();
app.use(express.json());
app.get("/client", buscarEmpresas);
app.get("/pool", buscarFiliais);
app.get("/empresas/:id", buscarEmpresaPorID);
app.get("/filiais/:id", buscarFilialPorID);
app.get("/pessoas/:id", buscarPessoaPorID);
export default app;